[pytest]
testpaths = apps
python_files = test_*.py
python_functions = test_*

addopts = -v

log_cli = true
log_cli_level = INFO

markers =
    integration: marks a test as an integration test
    regression: marks a test as a regression test
